SteamFinder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(path('', include('SteamID.urls')))

SteamID/urls.py
from django.urls import path
from .views import index, user_detail, search

app_name = 'SteamID'
urlpatterns = [
    path('', index, name='index'),
    path('<str:find>', search, name='search'),
    path('<int:steam_id>/', user_detail, name='user_detail'),
]

SteamID/models.py
from django.db import models


class User(models.Model):
    steam_id = models.CharField('Steam ID', unique=True, editable=False, max_length=20)
    nick = models.CharField('Nickname', max_length=500, null=True)
    url = models.URLField('Page', null=True)
    avatar_logo = models.URLField('Icon', null=True)
    avatar = models.URLField('Avatar', null=True)
    comment = models.IntegerField('Can comment', null=True)
    realname = models.CharField('Real name', max_length=500, null=True)
    created = models.DateTimeField('Created', null=True)
    country = models.CharField('Country', max_length=2, null=True)
    # BANS
    ban_community = models.BooleanField('Ban community', null=True)
    ban_VAC = models.BooleanField('VAC ban', null=True)
    ban_VAC_count = models.PositiveIntegerField('VAC bans', null=True)
    ban_games = models.PositiveIntegerField('Games ban', null=True)
    ban_economy = models.CharField('Ban economy', max_length=500, null=True)

    def __str__(self):
        return self.nick

    class Meta:
        verbose_name = 'Steam user'
        verbose_name_plural = 'Steam users'

SteamID/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from keys import STEAM_API_KEY
from .models import User
from .steam_api import get_steamid_from_url, SteamAPI
from .steam_user import SteamUserAdv


def index(request):
    return render(request, 'SteamID/HomePage.html')


def search(request, find):
    if 'steam' in request.GET:
        find = request.GET.get('steam')
        if not find.isnumeric():
            user = User.objects.filter(url=find)
            find = user[0].steam_id if user else get_steamid_from_url(find.lower())
    if find and find.isnumeric():
        return HttpResponseRedirect(reverse('SteamID:user_detail', args=(find,)))
    else:
        return render(request, 'SteamID/Error-page.html')


def user_detail(request, steam_id):
    user = None
    if type(steam_id) == int:
        steam = SteamAPI(TOKEN=STEAM_API_KEY)
        bans = steam.get_users_with_bans(steam_id)
        if bans:
            user = SteamUserAdv(bans[0])
            if user.visibility == 3:
                user.set_badges(steam.get_badges(steam_id))
                user.friends_all(steam.get_friends_as_users(steam_id))
                user.set_games(steam.get_owned_games(steam_id))
        else:
            return render(request, 'SteamID/Error-page.html')
    return render(request, 'SteamID/user-details.html', {'user': user})

templates/SteamID/Error-page.html
{% extends 'SteamID/Template.html' %}

{% load i18n %}

{% block title %}
    {% trans "Error Page" %}  - Steam User Finder
{% endblock %}

{% block content %}
    <div class="error_box">
        {% blocktrans %}
            Steam user data not found. Please enter URL steam user profile like
            <span style="color: yellow"><strong>"https://steamcommunity.com/id/slowlypoke/"</strong></span> or enter
            SteamID like <span style="color: yellow"><strong>"76561198217904428"</strong></span>
        {% endblocktrans %}
    </div>
{% endblock %}

templates/SteamID/HomePage.html
{% extends 'SteamID/Template.html' %}

{% block title %}Steam User Finder{% endblock %}

{% load i18n %}

{% block content %}

        <div class="info-block">
            <blockquote>
                {% blocktrans %}
                Steam is a video game digital distribution service by Valve. It was launched as a standalone software
                client
                in September 2003 as a way for Valve to provide automatic updates for their games, and expanded to
                include
                games from third-party publishers. Steam has also expanded into an online web-based and mobile digital
                storefront. Steam offers digital rights management (DRM), matchmaking servers, video streaming, and
                social
                networking services. It also provides the user with installation and automatic updating of games, and
                community features such as friends lists and groups, cloud saving, and in-game voice and chat
                functionality.
                {% endblocktrans %}
                <cite>{% trans "Wikipedia" %}</cite>
            </blockquote>
        </div>

{% endblock %}

templates/SteamID/Template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}

    {% endblock %}</title>

    {% load static %}
    {% load static i18n %}

    <link type="text/css" rel="stylesheet" href="{% static 'SteamID/css/template.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Caveat|Gabriela&display=swap&subset=cyrillic" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="{% static "SteamID/images/steam.ico" %}">
    <script src="{% static 'SteamID/js/jquery-3.4.1.min.js' %}"></script>

</head>
<body>
<script>
    $(window).on("load", function () {
        $(".loader-wrapper").fadeOut("slow");
    });
    $(document).ready(function () {
        $("#search-btn").click(function () {
            if ($("#search").val().length >= 1) {
                $(".loader-wrapper").show();
            }
        });
        $(".usr-id").click(function () {
            $(".loader-wrapper").show();
        });
    });
</script>


<div id="container">
    <div class="align-content-center">

        <div id="lang">
            <form action="{% url "set_language" %}" method="post">
                {% csrf_token %}
                <select name="language" onchange='{this.form.submit(); $(".loader-wrapper").show();}'>
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as langlist %}
                    {% get_current_language as CURR_LANG %}
                    {% for language in langlist %}
                        <option value="{{ language.code }}" {% if language.code == CURR_LANG %} selected {% endif %}>
                            {{ language.name_local|title }}
                        </option>
                    {% endfor %}
                </select>
            </form>
        </div>


        <h1><a href="/">Steam user Finder</a></h1>
        <div class="content">

            <div class="loader-wrapper">
                <h1 class="animate">{% trans "Loading data.<br> Please wait..." %}</h1>
            </div>

            {% include 'SteamID/searchbox.html' %}
            {% block content %}

            {% endblock %}
        </div>
    </div>
</div>
<div class="footer">
    <a href="https://money.yandex.ru/to/41001565554113" target="_blank"><img alt="yandex-money" title="Яндекс.Деньги"
            src="{% static "SteamID/images/ya_money.png" %}"></a>
</div>
</body>
</html>

templates/SteamID/searchbox.html
{% load i18n %}

<div class="box-left">
    <div class="info-block">
        {% blocktrans %}
            <p>Welcome to the Steam User Finder!<br>
                Using this service, you can get data about any Steam user, was he banned, who is his friends and what
                games he owns *
            </p><p style="color: #8F98A0">* If his profile is not hidden by privacy settings </p>
        {% endblocktrans %}
    </div>

    <form method="get" action="{% url 'SteamID:search' 'find_' %}" class="steamid">
        <div class="searchbox">
            <input id="search" placeholder="{% trans "Enter URL or SteamID" %}" required name="steam">
            {% load static %}
            <input id="search-btn" type="submit" value="">
        </div>
    </form>
</div>


<div class="info-block" style="width: 35%">
    {% blocktrans %}
        <p>How to Use!</p>
        <p>Enter Steam User URL or SteamID</p>
        <p>Wait a little</p>
        <p>Profit!</p>
        <p style="color: #8F98A0;  line-height: 20px;">Loading speed depends on how many friends user has and how many
            games he owns.</p>
    {% endblocktrans %}
</div>

<div style="clear: both"></div>

templates/SteamID/tables/UserFriends.html
<div class="tabs-line">
    {% for friends_stack in user.friends %}
        <button class="tablinks"
                onclick="openLink(event, 'tabid_{{ forloop.counter0 }}')">{{ forloop.counter }}</button>
    {% endfor %}
</div>

{% load static %}
{% load i18n %}


<div>
    {% for friends_stack in user.friends %}
        <div id="tabid_{{ forloop.counter0 }}" class="inline-group" style="display:none">
            <table class="table-data" style="width: 100%">
                <tr>
                    <th></th>
                    <th></th>
                    <th>{% trans "Name" %}</th>
                    <th>{% trans "Status" %}</th>
                    <th>{% trans "In game" %}</th>
                    <th>{% trans "Friend from" %}</th>
                    <th>{% trans "Ban" %}</th>
                </tr>
                {% for friend in friends_stack %}
                    <tr>
                        <td><a href="steam://friends/add/{{ friend.steam_id }}">
                            <img class="user-add" src="{% static 'SteamID/images/user.png' %}"
                                 title="{% trans "Add to friend" %}">
                        </a></td>
                        <td class="table-value"><img src="{{ friend.avatar_mini }}"></td>
                        <td class="table-value"><a class="usr-id"
                                                   href="{% url 'SteamID:search' friend.steam_id %}">{{ friend.nick }}</a>
                        </td>
                        <td class="table-value">{% if friend.state == 1 %}
                            <span style="color: #7FA94F">
                            {% else %} <span>
                                {% endif %}
                            {{ friend.get_status }}</span></td>
                        <td class="table-value">{% if friend.in_game %}
                            <span style="color: #7FA94F">{{ friend.in_game_info }}</span>{% endif %}</td>
                        <td class="table-value">{{ friend.friend_date|date:"d.m.Y" }}</td>
                        <td class="table-value" {% if friend.ban_VAC_count > 0 %}
                            style="background:linear-gradient(to bottom, rgba(255, 0, 0, 0.5) 0%, rgba(255, 0, 0, 0.1) 100%);"
                        {% endif %} >{{ friend.ban_VAC_count }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    {% endfor %}

</div>

{% include 'SteamID/tables/script_table.html' %}

templates/SteamID/tables/UserGames.html
<div class="tabs-line">
    {% for game_stack in user.games %}
        <button class="tablinks"
                onclick="openLink(event, 'gtabid_{{ forloop.counter0 }}')">{{ forloop.counter }}</button>
    {% endfor %}
</div>

{% load static %}
{% load i18n %}

<div>
    {% for game_stack in user.games %}
        <div id="gtabid_{{ forloop.counter0 }}" class="inline-group" style="display:none">
            <table class="table-data" style="width: 100%">
                <tr>
                    <th></th>
                    <th>{% trans "Game Name" %}</th>
                    <th>{% trans "Total playtime" %}</th>
                    <th>{% trans "Playtime on Windows" %}</th>
                    <th>{% trans "Playtime on Mac" %}</th>
                    <th>{% trans "Playtime on Linux" %}</th>
                </tr>
                {% for game in game_stack %}
                    <tr>
                        <td><a href="{{ game.app_url }}" target="_blank"><img src="{{ game.app_logo }}"></a> </td>
                        <td class="table-value"><a href="{{ game.app_url }}" target="_blank">{{ game.app_name }}</a></td>
                        <td class="table-value">{{ game.app_play_time }}</td>
                        <td class="table-value">{{ game.app_windows }}</td>
                        <td class="table-value">{{ game.app_mac }}</td>
                        <td class="table-value">{{ game.app_linux }}</td>

                    </tr>
                {% endfor %}
            </table>
        </div>
    {% endfor %}

</div>

{% include 'SteamID/tables/script_table.html' %}

templates/SteamID/tables/script_table.html
<script>
    function openLink(evt, LineName) {
        var i, tabcontent, tablinks;
        tabcontent = document.getElementsByClassName("inline-group");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }
        tablinks = document.getElementsByClassName("tablinks");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" active", "");
        }
        document.getElementById(LineName).style.display = "block";
        evt.currentTarget.className += " active";
    }
</script>

templates/SteamID/user-details.html
{% extends 'SteamID/Template.html' %}

{% block title %}
    {{ user.nick }} - Steam User Finder
{% endblock %}


{% load static %}
{% load i18n %}


{% block content %}
    <div id="avatar-content">
        <div class="avatar-logo">
            <img src="{{ user.avatar_big }}">
            <a href="steam://friends/add/{{ user.steam_id }}">
                <img class="user-add" src="{% static 'SteamID/images/user.png' %}" title="{% trans "Add to friend" %}">
            </a><br>
            <div class="avatar-data">
                <table class="table-data">
                    <tr>
                        <td>{% trans 'VAC ban' %}</td>
                        <td class="table-value"{% if user.ban_VAC %}
                            style="background:linear-gradient(to bottom, rgba(255, 0, 0, 0.5) 0%, rgba(255, 0, 0, 0.1) 100%);"
                        {% endif %}>{{ user.ban_VAC |yesno:"+,-" }}</td>
                    </tr>
                    <tr>
                        <td>{% trans 'VAC ban count' %}</td>
                        <td class="table-value">{{ user.ban_VAC_count }}</td>
                    </tr>
                    <tr>
                        <td>{% trans 'Ban community' %}</td>
                        <td class="table-value">{{ user.ban_community |yesno:"+,-" }}</td>
                    </tr>
                    <tr>
                        <td>{% trans 'Ban games' %}</td>
                        <td class="table-value">{{ user.ban_game }}</td>
                    </tr>
                    <tr>
                        <td>{% trans 'Ban economy' %}</td>
                        <td class="table-value">{{ user.ban_economy|default_if_none:"-" }}</td>
                    </tr>
                    <tr>
                        <td>{% trans 'Ban last' %}</td>
                        <td class="table-value">{{ user.days_to_ymd }}</td>
                    </tr>
                </table>
            </div>
        </div>
        <h2>{{ user.nick }}</h2>
        <div class="avatar-data">
            <table class="table-data">
                <tr>
                    <td>SteamID</td>
                    <td class="table-value">{{ user.steam_id }}</td>
                </tr>
                <tr>
                    <td>URL</td>
                    <td class="table-value"><a href="{{ user.url }}" title="Go to profile"
                                               target="_blank"> {{ user.url }} </a></td>
                </tr>
                <tr>
                    <td>{% trans 'Status' %}</td>
                    <td class="table-value">
                        {% if user.state == 1 %}
                            <span style="color: #7FA94F">
                        {% elif user.state == 2 %}
                            <span style="color: #516fa9">
                        {% else %}
                            <span>
                        {% endif %}
                        {{ user.get_status }}</span></td>
                </tr>
                <tr>
                    <td>{% trans 'Real Name' %}</td>
                    <td class="table-value">{{ user.realname|default_if_none:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Created' %}</td>
                    <td class="table-value">{{ user.created|default_if_none:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans 'LogOff' %}</td>
                    <td class="table-value">{{ user.logoff|default_if_none:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Game Info' %}</td>
                    <td class="table-value">
                        {% if user.in_game_info %}
                            <span style="color: #7FA94F">
                        {% else %}
                            <span>
                        {% endif %}
                        {{ user.in_game_info|default_if_none:"-" }}</span></td>
                </tr>
                <tr>
                    <td>{% trans 'Country' %}</td>
                    <td class="table-value">
                        {% if user.country %}
                            <img src="https://www.countryflags.io/{{ user.country }}/shiny/32.png"
                                 title="{{ user.country }}">
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td>{% trans 'Visible' %}</td>
                    <td class="table-value">{{ user.get_visibility }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Level' %}</td>
                    <td class="table-value">{{ user.level|default_if_none:"-" }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Experience' %}</td>
                    <td class="table-value">{{ user.xp|default:"-" }}/{{ user.progress_max|default:"0" }}</td>
                </tr>
            </table>
        </div>
        <div style="clear: both"></div>
    </div>

    {% if user.friends %}
        <h2>{% trans "Friends" %} ({{ user.friends_count }})</h2>
        {% include 'SteamID/tables/UserFriends.html' %}
    {% endif %}

    {% if user.games %}
        <h2>{% trans "Games" %} ({{ user.games_count }})</h2>
        {% include 'SteamID/tables/UserGames.html' %}
    {% endif %}


{% endblock %}